<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Inventory Logs Report</title>
    @vite(['resources/css/app.css'])
    <style>
        /* Only keep minimal print-specific styles */
        body {
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
        }
        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body class="p-8 text-gray-800 bg-white">
    {{-- Header --}}
    <div class="pb-4 mb-6 text-center border-b-2 border-[#8B7355]">
        <h1 class="m-0 text-2xl font-semibold text-[#3C2F23]">Inventory Logs Report</h1>
        <div class="mt-1 text-sm text-gray-600">{{ $spaName }} • {{ $branchName }}</div>
        <div class="mt-1 text-xs text-gray-500">
            @if($selectedMonth)
                Report for: {{ $selectedMonth }}
            @else
                All Logs
            @endif
            &nbsp;|&nbsp; Generated: {{ $generatedAt }}
        </div>
    </div>

    {{-- Summary Cards --}}
    <div class="flex justify-between p-3 mb-6 rounded-lg bg-[#F6EFE6]">
        <div class="text-sm">
            <span class="font-semibold text-[#3C2F23]">Total Logs:</span>
            <span class="ml-1">{{ $totalLogs }}</span>
        </div>
        <div class="text-sm">
            <span class="font-semibold text-[#3C2F23]">Branch:</span>
            <span class="ml-1">{{ $branchName }}</span>
        </div>
        <div class="text-sm">
            <span class="font-semibold text-[#3C2F23]">Generated:</span>
            <span class="ml-1">{{ $generatedAt }}</span>
        </div>
    </div>

    {{-- Logs Table --}}
    @if($logs->count() > 0)
        <div class="overflow-x-auto">
            <table class="w-full text-sm border-collapse">
                <thead>
                    <tr class="bg-[#8B7355]">
                        <th class="px-3 py-2 text-xs font-semibold tracking-wider text-left text-white uppercase">Description</th>
                        <th class="px-3 py-2 text-xs font-semibold tracking-wider text-left text-white uppercase">Date & Time</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($logs as $log)
                        <tr class="border-b border-gray-200 even:bg-gray-50">
                            <td class="px-3 py-2 text-gray-800">{{ $log->description }}</td>
                            <td class="px-3 py-2 text-gray-700">
                                {{ $log->logged_at?->format('M d, Y h:i A') ?? $log->created_at->format('M d, Y h:i A') }}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @else
        <div class="py-12 text-center text-gray-500">
            <p>No inventory logs found for the selected period.</p>
        </div>
    @endif

    {{-- Footer --}}
    <div class="pt-4 mt-8 text-xs text-center text-gray-500 border-t border-gray-200">
        <p>This report was automatically generated by the Levictas Spa System.</p>
        <p class="mt-1">&copy; {{ date('Y') }} {{ $spaName }}. All rights reserved.</p>
    </div>
</body>
</html>
