<?php

/*
|--------------------------------------------------------------------------
| Levictas Payroll — Statutory Configuration (locked data model v3)
|--------------------------------------------------------------------------
|
| SOURCE RULE: every number and rule below is transcribed ONLY from
| levictas-payroll-rates-sheet.md (Rev. 3, 2026-09-25). Each value cites the
| sheet section (§n) and the sheet's status:
|
|   OFFICIAL   read directly from a government document or site
|   VERIFY     consistent across secondary sources; official table is an image
|              that was not read — check the listed rows yourself
|   UNVERIFIED no official text found; documented default
|   DESIGN     not in the rates sheet at all; a Levictas choice (treat as UNVERIFIED)
|
| FORMAT: all money and rates are decimal STRINGS, consumed with bcmath by
| App\Services\Payroll\StatutoryCalculator. Never write floats here.
| No closures — this file must survive `php artisan config:cache`.
|
| VERSIONING
|  - `version` is written to payroll_runs.config_version. Bump it on ANY change.
|  - Rate blocks are LISTS of entries, each with `effective_from` (Y-m-d). The
|    calculator uses the entry with the latest effective_from <= the relevant
|    date. To change a rate, APPEND a new entry; never edit an entry that a
|    finalized run has used.
|  - `holidays` is keyed by calendar year (each row carries its own date).
|  - `components` is not date-versioned: component(code) takes no date, so a
|    flag change is a new `version` (see the note on that block).
|
*/

// DESIGN / UNVERIFIED: adoption date for blocks whose rates-sheet section gives
// no effective date (§5, §6). This is NOT a legal effective date — it is the
// first date Levictas applies these values. Earlier dates throw.
$adoptedFrom = '2026-01-01';

return [

    'version' => '2026.3',   // 2026.3: rates sheet Rev. 3 (hours_of_work: normal hours, unpaid meal period)
                            // 2026.2: rates sheet Rev. 2 (PhilHealth date, EEMR factors, 2027 holidays)

    /*
    |----------------------------------------------------------------------
    | SSS — §1 (RA 11199; SSS Circular 2024-006)
    |----------------------------------------------------------------------
    | Only parameters are stored; the 61-row bracket table is generated by
    | StatutoryCalculator::sssSchedule(). MSC is derived, never stored.
    | "Compensation" = all actual remuneration for employment incl. mandated
    |   COLA (§1, Sec. 8(f) — OFFICIAL).
    | "Monthly" for daily-paid = end of last payroll period of prior month to
    |   end of last payroll period of current month (§1, Sec. 8(h) — OFFICIAL).
    | IRR Sec. 8(f) items: salaries/wages, commission, bonuses except Christmas
    |   bonus, overtime, paid leave, COLA (§1 Rev. 2 — OFFICIAL). 13th-month pay is
    |   read as the Christmas-bonus exception (§1 Rev. 2 — VERIFY).
    */
    'sss' => [
        [
            // §1 "effective January 2025" (Circular 2024-006) — OFFICIAL.
            // Day-of-month not stated; 1st assumed.
            'effective_from' => '2025-01-01',

            'total_rate' => '0.15',          // §1 15% of MSC — OFFICIAL (must equal ee_rate + er_rate)
            'ee_rate'    => '0.05',          // §1 employee share 5% — OFFICIAL
            'er_rate'    => '0.10',          // §1 employer share 10% — OFFICIAL

            'min_msc' => '5000.00',          // §1 minimum MSC — OFFICIAL
            'max_msc' => '35000.00',         // §1 maximum MSC — OFFICIAL
            // Below-minimum / above-maximum earners contribute at min / max MSC
            // (§1, Sec. 4(a)(9) proviso — OFFICIAL).

            // Bracket structure — §1 — VERIFY against the Circular 2024-006 table image.
            'first_range_below' => '5250.00',   // compensation < 5,250 → min MSC
            'range_width'       => '500.00',    // each next range is ₱500 wide ...
            'msc_step'          => '500.00',    // ... and its MSC is +₱500
            'last_range_from'   => '34750.00',  // 34,750 and over → max MSC

            // MPF portion = MSC in excess of ₱20,000 up to max MSC
            // (§1, Sec. 4(a)(2) — OFFICIAL). The regular SS portion is MSC capped at 20,000.
            'mpf_msc_above' => '20000.00',

            // EC, employer only — §1 — VERIFY.
            'ec' => [
                'msc_threshold' => '15000.00',  // MSC < 15,000 → below; MSC >= 15,000 → at_or_above
                'below'         => '10.00',
                'at_or_above'   => '30.00',
            ],
        ],
    ],

    /*
    |----------------------------------------------------------------------
    | PhilHealth — §2 (Advisory 2025-0002)
    |----------------------------------------------------------------------
    | Base = Monthly Basic Salary (MBS): fixed basic rate. EXCLUDES sales
    | commission, overtime, allowances, 13th month, bonuses, and is NOT reduced
    | by undertime, tardiness, unpaid leave or absences (§2 — OFFICIAL).
    | MBS for monthly-paid and daily-paid staff = EEMR = daily rate × factor ÷ 12
    |   (§2 Rev. 2 — OFFICIAL, PhilHealth Circular 2018-0001; factors in
    |   `eemr_factors`, §10). So MBS comes from the pay RATE, never from summed
    |   payslip lines. Base-rate-0 staff: EEMR of the branch min_daily_wage
    |   (§2 Rev. 2 — UNVERIFIED design default, applied by the run engine).
    | The calculator takes MBS as an input; equivalentMonthlyRate() converts.
    */
    'philhealth' => [
        [
            // §2 Rev. 2: "applicable period of January 2025" — OFFICIAL.
            // 2026 applicability — VERIFY (no 2026 issuance; 2026 guides unchanged).
            'effective_from' => '2025-01-01',

            'rate'           => '0.05',       // §2 premium 5.0% — OFFICIAL
            'income_floor'   => '10000.00',   // §2 — OFFICIAL (premium ₱500)
            'income_ceiling' => '100000.00',  // §2 — OFFICIAL (premium ₱5,000)
            'employee_share' => '0.50',       // §2 EE/ER 50/50 — VERIFY (Circular 2020-0005 not read directly)
        ],
    ],

    /*
    |----------------------------------------------------------------------
    | Days-per-year factors (EEMR) — §10 (Rev. 2)
    |----------------------------------------------------------------------
    | EEMR = daily rate × factor ÷ 12; daily rate = monthly rate × 12 ÷ factor.
    | Factor is DERIVED from pay_basis and the number of weekly rest days in the
    | pay profile — never a spa setting (replaces spas.monthly_rate_divisor).
    | 393.5 (works every day incl. rest days) is reference-only in §10 and is
    | deliberately absent: a schedule with no weekly rest day throws.
    */
    'eemr_factors' => [
        [
            'effective_from' => '2010-03-05',   // §10 DOLE Advisory No. 001-10 date — VERIFY (text via Legaldex)
            'monthly' => '365',                 // §10 monthly-paid — VERIFY
            'daily_by_rest_days' => [
                1 => '313',                     // §10 daily-paid, 1 rest day/week — OFFICIAL (PhilHealth Circ. 2018-0001)
                2 => '261',                     // §10 daily-paid, 2 rest days/week — OFFICIAL (PhilHealth Circ. 2018-0001)
            ],
        ],
    ],

    /*
    |----------------------------------------------------------------------
    | Pag-IBIG / HDMF — §3 (HDMF Circular No. 460)
    |----------------------------------------------------------------------
    | Fund Salary = basic salary and other allowances; remuneration however
    | designated (§3 — OFFICIAL). Minimum-wage staff already exceed ₱10,000/month,
    | so the cap applies and component inclusion does not change the amount (§3 note).
    */
    'pagibig' => [
        [
            'effective_from' => '2024-02-01',   // §3 "effective February 2024" — OFFICIAL; 1st assumed

            'low_salary_max'  => '1500.00',     // §3 fund salary <= ₱1,500 uses `low` — OFFICIAL
            'low'             => ['ee_rate' => '0.01', 'er_rate' => '0.02'],  // §3 — OFFICIAL
            'high'            => ['ee_rate' => '0.02', 'er_rate' => '0.02'],  // §3 fund salary > ₱1,500 — OFFICIAL
            'max_fund_salary' => '10000.00',    // §3 → max ₱200 EE / ₱200 ER — OFFICIAL
        ],
    ],

    /*
    |----------------------------------------------------------------------
    | BIR withholding on compensation — §4 (Annex E, RR 11-2018) — OFFICIAL
    |----------------------------------------------------------------------
    | tax = base_tax + rate × (compensation − over)
    | The official ranges touch at whole pesos (e.g. 16,666 / 16,667), leaving
    | centavo gaps. Per §4's note, the bracket is chosen by the `over` thresholds:
    | the highest bracket whose `over` the compensation EXCEEDS; otherwise
    | bracket 1. The schedule is continuous at every `over`, so the tie choice
    | never changes the amount (asserted in tests).
    | `range` repeats the sheet's text for traceability only; code never reads it.
    */
    'bir_withholding' => [
        [
            'effective_from' => '2023-01-01',   // §4 "effective January 1, 2023 onwards" — OFFICIAL

            'semi_monthly' => [
                ['range' => '10,417 and below',  'over' => null,        'base_tax' => '0.00',     'rate' => '0.00'],
                ['range' => '10,417 – 16,666',   'over' => '10417.00',  'base_tax' => '0.00',     'rate' => '0.15'],
                ['range' => '16,667 – 33,332',   'over' => '16667.00',  'base_tax' => '937.50',   'rate' => '0.20'],
                ['range' => '33,333 – 83,332',   'over' => '33333.00',  'base_tax' => '4270.70',  'rate' => '0.25'],
                ['range' => '83,333 – 333,332',  'over' => '83333.00',  'base_tax' => '16770.70', 'rate' => '0.30'],
                ['range' => '333,333 and above', 'over' => '333333.00', 'base_tax' => '91770.70', 'rate' => '0.35'],
            ],

            // §4: "used only for reference/tests".
            'monthly' => [
                ['range' => '20,833 and below',  'over' => null,        'base_tax' => '0.00',      'rate' => '0.00'],
                ['range' => '20,833 – 33,332',   'over' => '20833.00',  'base_tax' => '0.00',      'rate' => '0.15'],
                ['range' => '33,333 – 66,666',   'over' => '33333.00',  'base_tax' => '1875.00',   'rate' => '0.20'],
                ['range' => '66,667 – 166,666',  'over' => '66667.00',  'base_tax' => '8541.80',   'rate' => '0.25'],
                ['range' => '166,667 – 666,666', 'over' => '166667.00', 'base_tax' => '33541.80',  'rate' => '0.30'],
                ['range' => '666,667 and above', 'over' => '666667.00', 'base_tax' => '183541.80', 'rate' => '0.35'],
            ],
        ],
    ],

    /*
    |----------------------------------------------------------------------
    | 13th month + other benefits tax exclusion — §5 — UNVERIFIED
    |----------------------------------------------------------------------
    | NIRC Sec. 32(B)(7)(e) as amended by RA 10963 (official text not read).
    | Per calendar year; THIRTEENTH_MONTH is taxable only above this cap.
    */
    'thirteenth_month_exemption_cap' => [
        [
            'effective_from' => $adoptedFrom,   // §5 gives no date — DESIGN adoption date
            'annual_cap'     => '90000.00',     // §5 — UNVERIFIED
        ],
    ],

    /*
    |----------------------------------------------------------------------
    | Minimum wage earner (MWE) exempt components — §5
    |----------------------------------------------------------------------
    | §5 (Rev. 2 — VERIFY; Soriano v. Sec. of Finance, G.R. 184450): statutory
    | minimum wage, holiday pay, overtime pay, night shift differential, hazard
    | pay are exempt; other compensation (commission, allowances) stays taxable,
    | and receiving it does NOT remove MWE status. Rest-day premium treated as
    | exempt (§5 — UNVERIFIED). MWE test (§5, UNVERIFIED design default): daily rate
    | (or monthly equivalent) <= home-branch min_daily_wage — applied by the
    | run engine, not here.
    |
    | Mapping to component codes (UNVERIFIED — the mapping is Levictas's):
    |   statutory minimum wage → BASIC, MINWAGE_TOPUP
    |   holiday pay            → HOLIDAY_PAY, HOLIDAY_PREM
    |   overtime pay           → OT
    |   night shift diff.      → NIGHT_DIFF
    |   rest-day premium       → RESTDAY_PREM
    |   hazard pay             → (no component code in the locked model)
    */
    'mwe_exempt_components' => [
        [
            'effective_from' => $adoptedFrom,   // §5 gives no date — DESIGN adoption date
            'codes' => [   // list is VERIFY; code mapping UNVERIFIED
                'BASIC',
                'MINWAGE_TOPUP',
                'HOLIDAY_PAY',
                'HOLIDAY_PREM',
                'OT',
                'NIGHT_DIFF',
                'RESTDAY_PREM',
            ],
        ],
    ],

    /*
    |----------------------------------------------------------------------
    | Labor multipliers — §6
    |----------------------------------------------------------------------
    | Daily rate = 100%; hourly rate = daily ÷ 8 (§6).
    |   Keys WITHOUT _ot : multiplier of the daily rate for the first 8 hours.
    |                      Applied per worked DAY, not pro-rated by hours: late /
    |                      undertime deductions are CUT in v3, so a short day
    |                      earns the full day (2026.3 — DESIGN, matches BASIC).
    |   Keys WITH _ot    : multiplier of the HOURLY rate per hour beyond 8.
    |   night_diff       : ADDITIVE +10% of the hourly rate, 22:00–06:00
    |                      (§6, Labor Code Art. 86 — OFFICIAL). On a premium day
    |                      it applies to that day's premium hourly rate
    |                      (§6 — UNVERIFIED, the higher-paying reading).
    |
    | Rules NOT keyed here (applied by the run engine):
    |  - Special (working) day = ordinary day (§6, DOLE LA 12-25 — OFFICIAL).
    |  - Special (non-working) day unworked = no work, no pay (§6 — OFFICIAL).
    |  - Regular holiday unworked is paid only if present or on paid leave on the
    |    workday immediately preceding; if that day is a rest/non-working day,
    |    look at the day before it (§6 — OFFICIAL).
    |  - Monthly-paid staff: no separate unworked-holiday pay line (§6 — UNVERIFIED).
    |  - Double holiday: not implemented; none in the 2026 list (§6 — UNVERIFIED).
    */
    'multipliers' => [
        [
            // §6 sources (Labor Code; DOLE LA 12-25; DOLE release 24 Mar 2026) give
            // no single effective date — DESIGN adoption date.
            'effective_from' => $adoptedFrom,

            'rates' => [
                'ordinary_ot'                 => '1.25',  // 125% of hourly — Art. 87; LA 12-25 — OFFICIAL
                'rest_day'                    => '1.30',  // 130% — Arts. 87, 93 — OFFICIAL
                'rest_day_ot'                 => '1.69',  // 130% × 130% — OFFICIAL
                'special_day'                 => '1.30',  // special non-working, not rest day — OFFICIAL
                'special_day_ot'              => '1.69',  // 130% × 130% — OFFICIAL
                'special_rest_day'            => '1.50',  // special non-working on rest day — LA 12-25 — OFFICIAL
                'special_rest_day_ot'         => '1.95',  // 150% × 130% — OFFICIAL
                'regular_holiday_worked'      => '2.00',  // 200% — Art. 94 — OFFICIAL
                'regular_holiday_ot'          => '2.60',  // 200% × 130% — OFFICIAL
                'regular_holiday_rest_day'    => '2.60',  // 200% × 130% — OFFICIAL
                'regular_holiday_rest_day_ot' => '3.38',  // 200% × 130% × 130% — OFFICIAL
                'regular_holiday_unworked'    => '1.00',  // 100%, subject to preceding-day rule — OFFICIAL
                'night_diff'                  => '0.10',  // +10% of hourly, additive — Art. 86 — OFFICIAL
            ],
        ],
    ],

    /*
    |----------------------------------------------------------------------
    | Hours of work — §6 (Rev. 3)
    |----------------------------------------------------------------------
    | normal_daily_hours   8 — hourly rate = daily ÷ 8 and OT starts after 8
    |                      hours (§6; Labor Code Art. 87 — OFFICIAL).
    | unpaid_meal_minutes  60 — employers must give not less than 60 minutes
    |                      off for regular meals, not counted as hours worked
    |                      when the employee is completely freed from duty
    |                      (§6 Rev. 3; Labor Code Art. 85 — VERIFY, text via a
    |                      non-government copy of P.D. 442).
    | Engine rule (§6 Rev. 3 — DESIGN/UNVERIFIED): OT hours =
    |   (time_out − time_in) − unpaid_meal_minutes − normal_daily_hours, floor 0.
    |   Assumes every shift long enough to reach OT includes one full meal
    |   break. DOLE-approved shortened meal periods are not modeled; one value
    |   applies to every spa.
    */
    'hours_of_work' => [
        [
            'effective_from'      => $adoptedFrom,  // §6 gives no date — DESIGN adoption date
            'normal_daily_hours'  => '8',           // §6 — OFFICIAL (Art. 87)
            'unpaid_meal_minutes' => '60',          // §6 Rev. 3 — VERIFY (Art. 85)
        ],
    ],

    /*
    |----------------------------------------------------------------------
    | National holidays — §7 (2026) and §7b (2027) — OFFICIAL
    |----------------------------------------------------------------------
    | 2026: Proclamations 1006 s. 2025, 1189 s. 2026, 1264 s. 2026 —
    |       12 regular, 8 special_non_working, 1 special_working.
    | 2027: Proclamation 1427 s. 2026 — 10 regular, 8 special_non_working,
    |       1 special_working. Eid'l Fitr / Eid'l Adha 2027 NOT YET DATED — add
    |       when proclaimed (new version). Local/city holidays
    | are not included. A holiday proclaimed later → add it here AND bump
    | `version`. A year with no list makes holidaysBetween() throw (fail loud;
    | never silently treat a year as holiday-free).
    */
    'holidays' => [
        2026 => [
            ['date' => '2026-01-01', 'name' => "New Year's Day",                           'type' => 'regular',             'proclamation' => '1006'],
            ['date' => '2026-02-17', 'name' => 'Chinese New Year',                         'type' => 'special_non_working', 'proclamation' => '1006'],
            ['date' => '2026-02-25', 'name' => 'EDSA People Power Revolution Anniversary', 'type' => 'special_working',     'proclamation' => '1006'],
            ['date' => '2026-03-20', 'name' => "Eid'l Fitr",                               'type' => 'regular',             'proclamation' => '1189'],
            ['date' => '2026-04-02', 'name' => 'Maundy Thursday',                          'type' => 'regular',             'proclamation' => '1006'],
            ['date' => '2026-04-03', 'name' => 'Good Friday',                              'type' => 'regular',             'proclamation' => '1006'],
            ['date' => '2026-04-04', 'name' => 'Black Saturday',                           'type' => 'special_non_working', 'proclamation' => '1006'],
            ['date' => '2026-04-09', 'name' => 'Araw ng Kagitingan',                       'type' => 'regular',             'proclamation' => '1006'],
            ['date' => '2026-05-01', 'name' => 'Labor Day',                                'type' => 'regular',             'proclamation' => '1006'],
            ['date' => '2026-05-27', 'name' => "Eid'l Adha",                               'type' => 'regular',             'proclamation' => '1264'],
            ['date' => '2026-06-12', 'name' => 'Independence Day',                         'type' => 'regular',             'proclamation' => '1006'],
            ['date' => '2026-08-21', 'name' => 'Ninoy Aquino Day',                         'type' => 'special_non_working', 'proclamation' => '1006'],
            ['date' => '2026-08-31', 'name' => 'National Heroes Day',                      'type' => 'regular',             'proclamation' => '1006'],
            ['date' => '2026-11-01', 'name' => "All Saints' Day",                          'type' => 'special_non_working', 'proclamation' => '1006'],
            ['date' => '2026-11-02', 'name' => "All Souls' Day",                           'type' => 'special_non_working', 'proclamation' => '1006'],
            ['date' => '2026-11-30', 'name' => 'Bonifacio Day',                            'type' => 'regular',             'proclamation' => '1006'],
            ['date' => '2026-12-08', 'name' => 'Feast of the Immaculate Conception',       'type' => 'special_non_working', 'proclamation' => '1006'],
            ['date' => '2026-12-24', 'name' => 'Christmas Eve',                            'type' => 'special_non_working', 'proclamation' => '1006'],
            ['date' => '2026-12-25', 'name' => 'Christmas Day',                            'type' => 'regular',             'proclamation' => '1006'],
            ['date' => '2026-12-30', 'name' => 'Rizal Day',                                'type' => 'regular',             'proclamation' => '1006'],
            ['date' => '2026-12-31', 'name' => 'Last Day of the Year',                     'type' => 'special_non_working', 'proclamation' => '1006'],
        ],
        2027 => [
            ['date' => '2027-01-01', 'name' => "New Year's Day",                           'type' => 'regular',             'proclamation' => '1427'],
            ['date' => '2027-02-06', 'name' => 'Chinese New Year',                         'type' => 'special_non_working', 'proclamation' => '1427'],
            ['date' => '2027-02-25', 'name' => 'EDSA People Power Revolution Anniversary', 'type' => 'special_working',     'proclamation' => '1427'],
            ['date' => '2027-03-25', 'name' => 'Maundy Thursday',                          'type' => 'regular',             'proclamation' => '1427'],
            ['date' => '2027-03-26', 'name' => 'Good Friday',                              'type' => 'regular',             'proclamation' => '1427'],
            ['date' => '2027-03-27', 'name' => 'Black Saturday',                           'type' => 'special_non_working', 'proclamation' => '1427'],
            ['date' => '2027-04-09', 'name' => 'Araw ng Kagitingan',                       'type' => 'regular',             'proclamation' => '1427'],
            ['date' => '2027-05-01', 'name' => 'Labor Day',                                'type' => 'regular',             'proclamation' => '1427'],
            ['date' => '2027-06-12', 'name' => 'Independence Day',                         'type' => 'regular',             'proclamation' => '1427'],
            ['date' => '2027-08-21', 'name' => 'Ninoy Aquino Day',                         'type' => 'special_non_working', 'proclamation' => '1427'],
            ['date' => '2027-08-30', 'name' => 'National Heroes Day',                      'type' => 'regular',             'proclamation' => '1427'],
            ['date' => '2027-11-01', 'name' => "All Saints' Day",                          'type' => 'special_non_working', 'proclamation' => '1427'],
            ['date' => '2027-11-02', 'name' => "All Souls' Day",                           'type' => 'special_non_working', 'proclamation' => '1427'],
            ['date' => '2027-11-30', 'name' => 'Bonifacio Day',                            'type' => 'regular',             'proclamation' => '1427'],
            ['date' => '2027-12-08', 'name' => 'Feast of the Immaculate Conception',       'type' => 'special_non_working', 'proclamation' => '1427'],
            ['date' => '2027-12-24', 'name' => 'Christmas Eve',                            'type' => 'special_non_working', 'proclamation' => '1427'],
            ['date' => '2027-12-25', 'name' => 'Christmas Day',                            'type' => 'regular',             'proclamation' => '1427'],
            ['date' => '2027-12-30', 'name' => 'Rizal Day',                                'type' => 'regular',             'proclamation' => '1427'],
            ['date' => '2027-12-31', 'name' => 'Last Day of the Year',                     'type' => 'special_non_working', 'proclamation' => '1427'],
        ],
    ],

    /*
    |----------------------------------------------------------------------
    | Pay components — locked data model v3
    |----------------------------------------------------------------------
    | kind matches payslip_lines.kind: earning | deduction | employer_share.
    | Flags describe earnings; deduction and employer_share codes carry
    | all-false flags by construction.
    |
    | Grounding:
    |  is_taxable             every earning except ADJ_EARNING_NONTAX and
    |                         THIRTEENTH_MONTH (the latter taxable only above
    |                         thirteenth_month_exemption_cap).
    |  in_13th_month_basis    BASIC, COMMISSION, MINWAGE_TOPUP only. DOLE 13th-month
    |                         advisory excludes overtime, premium, night
    |                         differential, holiday pay, allowances not integrated
    |                         into basic; commission included per Philippine
    |                         Duplicators v. NLRC. MINWAGE_TOPUP is UNVERIFIED.
    |  counts_toward_min_wage BASIC and COMMISSION only (DOLE: workers paid by
    |                         results must receive at least the minimum wage for
    |                         normal hours). COMMISSION is UNVERIFIED-by-policy.
    |  in_sss_compensation    every earning except THIRTEENTH_MONTH and
    |                         ADJ_EARNING_NONTAX (RA 11199 Sec. 8(f): all actual
    |                         remuneration; IRR lists commission — OFFICIAL).
    |                         THIRTEENTH_MONTH exclusion = IRR Christmas-bonus
    |                         exception — VERIFY (§1 Rev. 2).
    |  in_philhealth_mbs      BASIC only (Advisory 2025-0002 excludes commission,
    |                         overtime, allowances, 13th month). DOCUMENTATION
    |                         FLAG ONLY: the engine must NOT sum lines for PhilHealth;
    |                         MBS = EEMR of the pay rate (§2 Rev. 2 — OFFICIAL).
    |  in_pagibig_fund_salary BASIC and ALLOWANCE (Circular 460: basic salary and
    |                         other allowances). Other earnings false — UNVERIFIED;
    |                         immaterial for minimum-wage staff because the ₱10,000
    |                         cap is already reached (§3 note).
    |
    | Not date-versioned: a flag change requires a new `version`.
    */
    'components' => [

        // ---- Earnings ------------------------------------------------------
        'BASIC' => [
            'kind' => 'earning', 'label' => 'Basic Pay',
            'is_taxable' => true, 'in_13th_month_basis' => true, 'counts_toward_min_wage' => true,
            'in_sss_compensation' => true, 'in_philhealth_mbs' => true, 'in_pagibig_fund_salary' => true,
        ],
        'COMMISSION' => [
            'kind' => 'earning', 'label' => 'Commission',
            'is_taxable' => true, 'in_13th_month_basis' => true,
            'counts_toward_min_wage' => true,        // UNVERIFIED-by-policy
            'in_sss_compensation' => true, 'in_philhealth_mbs' => false,
            'in_pagibig_fund_salary' => false,       // UNVERIFIED
        ],
        'ALLOWANCE' => [
            'kind' => 'earning', 'label' => 'Allowance',
            'is_taxable' => true, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => true, 'in_philhealth_mbs' => false, 'in_pagibig_fund_salary' => true,
        ],
        'OT' => [
            'kind' => 'earning', 'label' => 'Overtime Pay',
            'is_taxable' => true, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => true, 'in_philhealth_mbs' => false,
            'in_pagibig_fund_salary' => false,       // UNVERIFIED
        ],
        'RESTDAY_PREM' => [
            'kind' => 'earning', 'label' => 'Rest Day Premium',
            'is_taxable' => true, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => true, 'in_philhealth_mbs' => false,
            'in_pagibig_fund_salary' => false,       // UNVERIFIED
        ],
        'HOLIDAY_PAY' => [
            'kind' => 'earning', 'label' => 'Holiday Pay',
            'is_taxable' => true, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => true, 'in_philhealth_mbs' => false,
            'in_pagibig_fund_salary' => false,       // UNVERIFIED
        ],
        'HOLIDAY_PREM' => [
            'kind' => 'earning', 'label' => 'Holiday Premium',
            'is_taxable' => true, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => true, 'in_philhealth_mbs' => false,
            'in_pagibig_fund_salary' => false,       // UNVERIFIED
        ],
        'NIGHT_DIFF' => [
            'kind' => 'earning', 'label' => 'Night Differential',
            'is_taxable' => true, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => true, 'in_philhealth_mbs' => false,
            'in_pagibig_fund_salary' => false,       // UNVERIFIED
        ],
        'MINWAGE_TOPUP' => [
            'kind' => 'earning', 'label' => 'Minimum Wage Top-up',
            'is_taxable' => true,
            'in_13th_month_basis' => true,           // UNVERIFIED
            'counts_toward_min_wage' => false,
            'in_sss_compensation' => true, 'in_philhealth_mbs' => false,
            'in_pagibig_fund_salary' => false,       // UNVERIFIED
        ],
        'THIRTEENTH_MONTH' => [
            'kind' => 'earning', 'label' => '13th Month Pay',
            'is_taxable' => false,                   // taxable only above thirteenth_month_exemption_cap
            'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false,          // VERIFY: IRR Christmas-bonus exception (§1 Rev. 2)
            'in_philhealth_mbs' => false,
            'in_pagibig_fund_salary' => false,       // UNVERIFIED
        ],
        'ADJ_EARNING' => [
            'kind' => 'earning', 'label' => 'Adjustment (Earning)',
            'is_taxable' => true, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => true, 'in_philhealth_mbs' => false,
            'in_pagibig_fund_salary' => false,       // UNVERIFIED
        ],
        'ADJ_EARNING_NONTAX' => [
            'kind' => 'earning', 'label' => 'Adjustment (Non-taxable)',
            'is_taxable' => false, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false, 'in_philhealth_mbs' => false,
            'in_pagibig_fund_salary' => false,       // UNVERIFIED
        ],

        // ---- Employee deductions ------------------------------------------
        // Net-pay application order (locked model): SSS_EE, PHIC_EE, HDMF_EE,
        // WTAX, LOAN_DEDUCTION, OTHER_DEDUCTION, ADJ_DEDUCTION.
        'SSS_EE' => [
            'kind' => 'deduction', 'label' => 'SSS Contribution',   // SS + MPF employee share
            'is_taxable' => false, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false, 'in_philhealth_mbs' => false, 'in_pagibig_fund_salary' => false,
        ],
        'PHIC_EE' => [
            'kind' => 'deduction', 'label' => 'PhilHealth Contribution',
            'is_taxable' => false, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false, 'in_philhealth_mbs' => false, 'in_pagibig_fund_salary' => false,
        ],
        'HDMF_EE' => [
            'kind' => 'deduction', 'label' => 'Pag-IBIG Contribution',
            'is_taxable' => false, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false, 'in_philhealth_mbs' => false, 'in_pagibig_fund_salary' => false,
        ],
        'WTAX' => [
            'kind' => 'deduction', 'label' => 'Withholding Tax',
            'is_taxable' => false, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false, 'in_philhealth_mbs' => false, 'in_pagibig_fund_salary' => false,
        ],
        'LOAN_DEDUCTION' => [
            'kind' => 'deduction', 'label' => 'Loan Deduction',
            'is_taxable' => false, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false, 'in_philhealth_mbs' => false, 'in_pagibig_fund_salary' => false,
        ],
        'OTHER_DEDUCTION' => [
            'kind' => 'deduction', 'label' => 'Other Deduction',
            'is_taxable' => false, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false, 'in_philhealth_mbs' => false, 'in_pagibig_fund_salary' => false,
        ],
        'ADJ_DEDUCTION' => [
            'kind' => 'deduction', 'label' => 'Adjustment (Deduction)',
            'is_taxable' => false, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false, 'in_philhealth_mbs' => false, 'in_pagibig_fund_salary' => false,
        ],

        // ---- Employer shares (not deducted from the employee) --------------
        'SSS_ER' => [
            'kind' => 'employer_share', 'label' => 'SSS (Employer)',  // SS + MPF employer share
            'is_taxable' => false, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false, 'in_philhealth_mbs' => false, 'in_pagibig_fund_salary' => false,
        ],
        'SSS_EC' => [
            'kind' => 'employer_share', 'label' => 'SSS EC (Employer)',
            'is_taxable' => false, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false, 'in_philhealth_mbs' => false, 'in_pagibig_fund_salary' => false,
        ],
        'PHIC_ER' => [
            'kind' => 'employer_share', 'label' => 'PhilHealth (Employer)',
            'is_taxable' => false, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false, 'in_philhealth_mbs' => false, 'in_pagibig_fund_salary' => false,
        ],
        'HDMF_ER' => [
            'kind' => 'employer_share', 'label' => 'Pag-IBIG (Employer)',
            'is_taxable' => false, 'in_13th_month_basis' => false, 'counts_toward_min_wage' => false,
            'in_sss_compensation' => false, 'in_philhealth_mbs' => false, 'in_pagibig_fund_salary' => false,
        ],
    ],

];
