<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'DejaVu Sans', 'Helvetica', 'Arial', sans-serif; color: #2D3748; font-size: 13px; margin: 0; padding: 40px; }
        .header { display: table; width: 100%; border-bottom: 2px solid #8B7355; padding-bottom: 20px; margin-bottom: 30px; }
        .header .brand { display: table-cell; vertical-align: middle; }
        .header .brand-name { font-size: 22px; font-weight: bold; color: #8B7355; }
        .header .brand-tagline { font-size: 10px; letter-spacing: 2px; color: #718096; }
        .header .status { display: table-cell; text-align: right; vertical-align: middle; }
        .status-badge { display: inline-block; padding: 6px 16px; border-radius: 20px; background-color: #DCFCE7; color: #15803D; font-weight: bold; font-size: 12px; }
        h1 { font-size: 18px; margin-bottom: 4px; color: #1A202C; }
        .subtext { color: #718096; margin-bottom: 30px; }
        table.details { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        table.details td { padding: 10px 0; border-bottom: 1px solid #E2E8F0; }
        table.details td.label { color: #718096; width: 40%; }
        table.details td.value { font-weight: bold; text-align: right; }
        .total-row td { border-top: 2px solid #2D3748; border-bottom: none; padding-top: 16px; font-size: 16px; }
        .total-row td.value { color: #15803D; }
        .footer { margin-top: 50px; text-align: center; font-size: 11px; color: #A0AEC0; }
    </style>
</head>
<body>

    <div class="header">
        <div class="brand">
            <div class="brand-name">{{ $spa->name }}</div>
            <div class="brand-tagline">SPA | WELLNESS</div>
        </div>
        <div class="status">
            <span class="status-badge">PAID</span>
        </div>
    </div>

    <h1>Payment Receipt</h1>
    <p class="subtext">{{ ucfirst($subscription->business_tier) }} Tier Upgrade</p>

    <table class="details">
        <tr>
            <td class="label">Billed To</td>
            <td class="value">
                {{ trim(($spa->owner->first_name ?? '') . ' ' . ($spa->owner->last_name ?? '')) }}<br>
                <span style="font-weight: normal; color: #718096;">{{ $spa->owner->email ?? '' }}</span>
            </td>
        </tr>
        <tr>
            <td class="label">Payment ID</td>
            <td class="value">{{ $subscription->paymongo_payment_id ?? $subscription->paymongo_checkout_id }}</td>
        </tr>
        <tr>
            <td class="label">Payment Date</td>
            <td class="value">{{ $subscription->starts_at?->format('F d, Y h:i A') ?? $subscription->created_at->format('F d, Y h:i A') }}</td>
        </tr>
        <tr>
            <td class="label">Payment Method</td>
            <td class="value">{{ $subscription->payment_method ? ucfirst($subscription->payment_method) : 'GCash' }}</td>
        </tr>
        <tr>
            <td class="label">Subscription Valid Until</td>
            <td class="value">{{ $subscription->expires_at?->format('F d, Y') ?? '—' }}</td>
        </tr>
        <tr class="total-row">
            <td class="label">Total Paid</td>
            <td class="value">₱ {{ number_format($subscription->amount, 2) }}</td>
        </tr>
    </table>

    <div class="footer">
        This is an official receipt for your subscription payment.<br>
        Generated by Levictas &middot; {{ now()->format('F d, Y') }}
    </div>

</body>
</html>